# Generated by Django 3.1.5 on 2021-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datetime',
            new_name='date_time',
        ),
    ]
