# Generated by Django 3.1.5 on 2021-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210106_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_time',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='date_time',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
