# Generated by Django 3.1.5 on 2021-01-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210106_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='date',
            new_name='dat',
        ),
        migrations.RenameField(
            model_name='date_time',
            old_name='time',
            new_name='tim',
        ),
    ]
