# Generated by Django 3.1.5 on 2021-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210106_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_time',
            name='status',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
